config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'top#index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]

  resources :pasts, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/past.rb
class Past < ApplicationRecord
  validates :times, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :last_name, presence: true, length: { maximum: 255 }
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name_kana, presence: true, length: { maximum: 255 }
  validates :first_name_kana, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true, presence: true

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to login_path
  end
end

app/controllers/pasts_controller.rb
class PastsController < ApplicationController
  def index
    @pasts = Past.all.order(times: :asc)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to pasts_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :last_name, :first_name,:last_name_kana, :first_name_kana)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pasts_helper.rb
module PastsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PTExam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% if logged_in? %>
    <%= render 'shared/header' %>
  <% else %>
    <%= render 'shared/before_login_header' %>
  <% end %>
  <%= render 'shared/flash_message.html' %>
    <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pasts/_past.html.erb
<li class="list-group-item">
  <a href="/pasts/<%= past.times %>">第<%= past.times %>回</a>
</li>

app/views/pasts/index.html.erb
<div class="container pt-3">
  <h2><%= t('.title') %></h2>
  <!-- 過去問一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <ul class="list-group">
          <% if @pasts.present? %>
            <%= render @pasts %>
          <% else %>
            <p><%= t('.no_result') %></p>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <img src="logo.png" />
    <% end %>

    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to (t 'defaults.login'), login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2022. PT Exam</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <a class='navbar-brand' href='/'>
      PT Exam
    </a>
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ml-auto main-nav align-items-center'>
        <li class='nav-item'>
          <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            学習する
          </a>
        </li>

        <%# <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            学習する
          </a>

          <div class='dropdown-menu dropdown-menu-right'>
            <a class='dropdown-item' href='#'>基礎医学</a>
            <a class='dropdown-item' href='#'>臨床医学</a>
            <a class='dropdown-item' href='#'>基礎理学療法学</a>
            <a class='dropdown-item' href='#'>障害別理学療法治療学</a>
          </div>
        </li> %>

        <li class='nav-item'>
          <%= link_to Past.model_name.human, pasts_path, class: 'nav-link' %>
        </li>

        <%# <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            過去問
          </a>

          <div class='dropdown-menu dropdown-menu-right'>
            <a class='dropdown-item' href='#'>第31回</a>
            <a class='dropdown-item' href='#'>第32回</a>
            <a class='dropdown-item' href='#'>第33回</a>
            <a class='dropdown-item' href='#'>第34回</a>
          </div>
        </li> %>

        <li class='nav-item'>
          <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            成績
          </a>
        </li>

        <li class='nav-item'>
          <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            対策問題
          </a>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='header-profile'>
            <%= image_tag 'sample', size: '40x40', class: 'rounded-circle mr15'%>
          </a>
          <div class='dropdown-menu dropdown-menu-right'>
            <div class='dropdown-item'><%= current_user.decorate.full_name %></div>
            <div class='dropdown-divider'></div>
            <%= link_to (t 'profiles.show.title'), '#', class: 'dropdown-item' %>
            <%= link_to (t 'defaults.logout'), logout_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      </ul>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/top/index.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>PT Exam</h1>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t '.title' %></h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email, User.human_attribute_name(:email) %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, User.human_attribute_name(:password) %>
          <%= f.password_field :password, class: 'form-control' %> </div>
        <div class="actions">
          <%= f.submit (t 'defaults.login'), class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to (t 'user_sessions.new.to_register_page'), new_user_path %>
        <a href="#"><%= (t 'user_sessions.new.password_forget') %></a>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= (t 'users.new.title') %></h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name_kana %>
          <%= f.text_field :last_name_kana, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :first_name_kana %>
          <%= f.text_field :first_name_kana, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit (t 'defaults.register'), class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <a href="/login"><%= (t 'users.new.to_login_page') %></a>
      </div>
    </div>
  </div>
</div>